---
# Configure a TOR hidden service for remote access without a public IP
#ok - name: "Setup TOR"
#ok   hosts: all
#ok   tags: tor
#ok   become: true
#ok   roles:
#ok     - role: tor
#ok       when: enable_tor

## Configure the server itself
#- name: configure HomelabOS
#  hosts: all
#  become: true
#  # gather_facts: "True"
#  tags: common
#  roles:
#    # Install Docker, configure basic server settings
#    - homelabos_common

#ok - name: "Deploy Bastion Host with Wireguard"
#ok   hosts: all
#ok   tags: bastion
#ok   become: true
#ok   tasks:
#ok     - include_role:
#ok         name: homelabos_wireguard
#ok         when: bastion.enable == True

# Install and configure HomelabOS base services
- name: Install and configure HomelabOS base services
  hosts: all
  tags:
    - deploy
  roles:
    - homelabos_api_deploy

  # Install and configure HomelabOS services
- name: Install and configure HomelabOS services
  hosts: all
  tags:
    - deploy_service
  roles:
    - homelabos_api_deploy_service
