---
- any_errors_fatal: true
  become: 'True'
  become_method: sudo
  gather_facts: 'False'
  hosts: all
  name: Install python (required by Ansible).
  pre_tasks:
    - name: Update Apt Cache
      raw: sudo apt-get update
      run_once: true
    - name: Install Python
      raw: >-
        sudo apt-get -y install python-simplejson python3 python3-simplejson
        python3-pip python3-virtualenv python3-passlib python3-openssl
      run_once: true
    - name: Configure python and pip
      raw: >-
        sudo apt-get -y purge python-simplejson && if [ ! -e /usr/bin/pip ];
        then ln -s pip3 /usr/bin/pip ; fi && if [[ ! -e /usr/bin/python ]]; then
        ln -sf /usr/bin/python3 /usr/bin/python ; fi
      run_once: true
  vars:
    ansible_python_interpreter: /usr/bin/python3
- become: true
  become_method: sudo
  hosts: all
  name: Setup TOR
  roles:
    - role: tor
      when: enable_tor
  tags: tor
- become: true
  hosts: all
  name: configure HomelabOS
  roles:
    - homelabos_common
  tags: common
- become: true
  become_method: sudo
  hosts: all
  name: Deploy Bastion Host with Wireguard
  tags: bastion
  tasks:
    - include_role:
        name: homelabos_wireguard
      when: bastion.enable == True
- become: true
  hosts: homelabos
  name: Install and configure HomelabOS services
  roles:
    - homelabos_deploy
  tags:
    - homelabos
    - deploy
