---
###############################
## What this playbook does:
## - Deploys the hlos web interface
###############################
- name: Create HomeLabOS Web directory
  file:
    path: "{{ volumes_root }}/homelabos-web"
    state: directory
  
- name: Copy HomeLabOS Web docker-compose.yml file into place.
  template:
    src: docker-compose.hlos-web.yml.j2
    dest: "{{ volumes_root }}/homelabos-web/docker-compose.yml"
#  vars:
#    tor_domain: "{{ tor_http_domain_file.stdout | default('') }}"

- name: Configure HomeLabOS Web systemd service.
  template:
    src: service.j2
    dest: /etc/systemd/system/homelabos-web.service

- name: Start HomeLabOS Web
  systemd:
    name: homelabos-web
    enabled: "yes"
    daemon-reload: "yes"
    state: started
