---
###############################
## What this playbook does:
## - Deploys the hlos web interface
###############################
- name: Copy vault password file to remote
  copy:
    src: "{{ lookup('env', 'HOME') }}/.homelabos_vault_pass"
    dest: "/home/{{ user_name }}/.homelabos_vault_pass"

- name: Copy ansible-api Docker file to remote
  copy:
    src: Dockerfile
    dest: "{{ volumes_root }}/ansible-api/docker/"

- name: Copy docker build files into place
  template:
    src: templates/entrypoint.sh.j2
    dest: "{{ volumes_root }}/ansible-api/docker/entrypoint.sh"

- name: Build ansible-api image
  docker_image:
    name: ansible-api
    tag: latest
    build:
      path: "{{ volumes_root }}/ansible-api/docker"
      pull: true
      rm: true
    source: build
    state: present

- name: Copy docker-compose into place
  template:
    src: docker-compose.yml.j2
    dest: "{{ volumes_root }}/ansible-api/docker-compose.yml"

- name: Configure ansible-api systemd service.
  template:
    src: service.j2
    dest: /etc/systemd/system/ansible-api.service
  become: true

- name: Start ansible-api
  systemd:
    name: ansible-api
    enabled: true
    daemon-reload: true
    state: started
  become: true
