---
#####################################
## What this playbook does:
## - Retrieve GID/UID for hlos user - used when setting up NAS drives
## - Tag: host_deps
##     Bootstrap server with software needs
## - Tag: create_user
##     Create the hlos user account. Can be run with host_deps
## - Tag: deploy_base
##     Copy down the HLOS repository
##     Run as the hlos user (i.e. change ansible cfg to switch to the new user!)
## - Tag: deploy_after_config
##     Setup remaining things after the config has been created. These tasks depend on variables set there.
##     Traefik, Tor, NAS/Samba
#####################################
- name: Import Create User tasks
  import_tasks: create_user.yml
  tags:
    - create_user

- name: Import Docker installation tasks
  import_tasks: docker.yml
  tags:
    - deploy_base

- name: Import Install HomeLabOS tasks
  import_tasks: deploy.yml
  tags:
    - deploy_base

- name: Import ansible_api installation tasks
  import_role:
    name: homelabos_ansible_api
  tags:
    - deploy_base

- name: Import hlos_web installation tasks
  import_role:
    name: homelabos_web
  tags:
    - deploy_base
  
#- name: Get UID of {{ user_name }}
#  command: id -u {{ user_name }}
#  register: uid_output
#
#- name: Get GID of {{ user_name }}
#  command: id -g {{ user_name }}
#  register: gid_output
#  
#- name: Import NAS/Directory tasks
#  import_tasks: nas_dirs.yml
#  tags:
#    - deploy_after_config
#  when: nas_enable is defined and nas_enable|bool
#
#- name: Import Traefik tasks
#  import_tasks: traefik.yml
#  tags:
#    - deploy_after_config
#
#- name: Import Tor tasks
#  import_tasks: tor.yml
#  tags:
#    - deploy_after_config
#